### ISSUE TITLE
Which frequency analysis in THz domain of NH3 is more reliable, CCSD(T) or MP2

### ISSUE THREAD

**Issue by xiongyan21** [kzfm/pygamess#14]
With GAMESS, for NH3, 6-311++G(2d,2p) MP2 optimization and subsequent semi-numerical  frequency analysis gives the following in THz domain
 MODE FREQ(CM**-1)  SYMMETRY  RED. MASS  IR INTENS.
     1      18.598    A        1.039865    1.176355
     2       0.804    A        4.501691    0.003434
     3       0.546    A        4.240721    0.001758
     4       0.296    A        4.183416    0.000286
     5       7.081    A        1.016050    0.360270
     6      19.062    A        1.030709    1.504469
CCSD(T) full numerical gives
                       1           2           3           4           5
       FREQUENCY:        21.13        7.35        3.64        3.76       25.01  
        SYMMETRY:         A           A           A           A           A   
    REDUCED MASS:      1.02297     4.18483     4.27262     4.18271     1.03968

                            6         
       FREQUENCY:        28.50    
        SYMMETRY:         A          
    REDUCED MASS:      1.04207

_Quantitative analysis of ammonia by THz time-domain spectroscopy_ gives the experimental 0.572THz.

Which is more reliable?

It seems B3LYP one is far away

 MODE FREQ(CM**-1)  SYMMETRY  RED. MASS  IR INTENS.
     1      85.137    A        1.040961    1.379277
     2      25.494    A        1.010339    0.103266
     3       0.037    A        4.256342    0.000001
     4       0.017    A        4.257583    0.000000
     5       0.074    A        4.253231    0.000001
     6      57.394    A        1.043004    1.454178

There are no warnings and notes in the above three calculations.

Very Best Regards!

**Comment by kzfm** [comment]
Hi, @xiongyan21,

Sorry for late replying, but you should post the GAMESS-related question into GAMESS ML, https://groups.google.com/g/gamess?pli=1

Pygamess is a simple GAMESS python wrapper library.
