### ISSUE TITLE
Basis sets

### ISSUE THREAD

**Issue by spalgit** [kzfm/pygamess#16]
Hi, I am trying to use B3LYP/6-311G(d,p) functional and basis set for geometry optimization of aromatic nitriles. I am not successful as I get basis-set not found . Can you please help? Is it possible to do that with pygamess?

Thanks,
Sandeep

**Comment by kzfm** [comment]
Hi, Sandeep,
You can use B3LYP/6-311G(d,p) function as follows:

```
g.options({'basis':{'gbasis': 'N311', 'ngauss': '6', 'ndfunc':'1', 'npfunc':'1', 'diffsp': '.true.', 'diffs': '.true.'}})
g.dft_type("B3LYP")
```
and you can check GAMESS input as `print(g.input(m))`.

However, this method is complicated and 6-311G(d,p) basissets may be added in the next version.

Best,
Kaz
